RandomCatFact/Models/CatFact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RandomCatFact.Models
{
    public class CatFact
    {
        public string Fact { get; set; }
    }
}

RandomCatFact/Controllers/CatFactController.cs
using Newtonsoft.Json;
using RandomCatFact.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace RandomCatFact.Controllers
{
    public class CatFactController : Controller
    {
        [HandleError]
        // GET: CatFact/Random
        public ActionResult Random()
        {
            GetRandomCatFact();
            CatFact fact = GetRandomCatFact();
            return View(fact);
        }
        protected CatFact GetRandomCatFact()
        {
            string json = "";
            WebRequest request = WebRequest.Create(ConfigurationManager.AppSettings["APIRandomCatFact"]);
            request.Credentials = CredentialCache.DefaultCredentials;
            WebResponse response = request.GetResponse();
            using (Stream dataStream = response.GetResponseStream())
            {
                StreamReader reader = new StreamReader(dataStream);
                json = reader.ReadToEnd();
            }
            response.Close();
            CatFact fact = JsonConvert.DeserializeObject<CatFact>(json);
            return fact;
        }
    }
}

RandomCatFact/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RandomCatFact.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

RandomCatFact/Views/CatFact/Random.cshtml
@model RandomCatFact.Models.CatFact
@{
    ViewBag.Title = "Random Cat Fact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron">
    <h2>@Model.Fact</h2>

    <p><a href="~/CatFact/Random" class="btn btn-primary btn-lg">Another Random Cat Fact &raquo;</a></p>

</div>

RandomCatFact/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Cat Facts</h1>
    <p class="lead">These are random cat facts from https://catfact.ninja which is a Web API, and the facts are returned as Json.</p>
    <p><a href="~/CatFact/Random" class="btn btn-primary btn-lg">Random Cat Fact &raquo;</a></p>
</div>

RandomCatFact/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cat Facts", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Random Cat Fact", "Random", "CatFact")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>